# f1 = input("Enter Fruit Number 1")
# f2 = input("Enter Fruit Number 2")
# f3 = input("Enter Fruit Number 3")
# f4 = input("Enter Fruit Number 4")
# f5 = input("Enter Fruit Number 5")
# f6 = input("Enter Fruit Number 6")
# f7 = input("Enter Fruit Number 7")
# myFruitList = [f1, f2, f3, f4, f5, f6, f7]
# print(myFruitList)
m1 = int(input("Enter marks for student 1: "))
m2 = int(input("Enter marks for student 2: "))
m3 = int(input("Enter marks for student 3: "))
m4 = int(input("Enter marks for student 4: "))
m5 = int(input("Enter marks for student 5: "))
m6 = int(input("Enter marks for student 6: "))
m7 = int(input("Enter marks for student 7: "))
mylist = [m1, m2, m3, m4, m5, m6, m7]
mylist.sort()
print(mylist)
